# Generated by Django 4.1.7 on 2023-04-26 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('skill_Id', models.IntegerField()),
                ('Skill_Category', models.CharField(max_length=200)),
                ('Skills_Name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Skillsmatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(max_length=200)),
                ('Is_Trained', models.CharField(max_length=4)),
                ('Is_Certified', models.CharField(max_length=4)),
                ('total_experience', models.CharField(max_length=10)),
                ('certifications', models.CharField(max_length=100)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('created_Date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsapp.skillset')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsapp.member')),
            ],
        ),
    ]
