# Generated by Django 4.1.7 on 2023-04-27 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillsapp', '0002_rename_skill_skillsmatrix_skills_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillsmatrix',
            name='created_Date',
        ),
    ]
