# Generated by Django 4.1.7 on 2023-05-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsapp', '0003_remove_skillsmatrix_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillsmatrix',
            name='assessment_date',
        ),
        migrations.AddField(
            model_name='skillsmatrix',
            name='certified_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='skillsmatrix',
            name='training_name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
